USE CadastroEscolar;

SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM matriculas;
DELETE FROM turmas;
DELETE FROM alunos;
DELETE FROM salas;
DELETE FROM cursos;

SET FOREIGN_KEY_CHECKS = 1;

ALTER TABLE matriculas AUTO_INCREMENT = 1;
ALTER TABLE turmas AUTO_INCREMENT = 1;
ALTER TABLE alunos AUTO_INCREMENT = 1;
ALTER TABLE salas AUTO_INCREMENT = 1;
ALTER TABLE cursos AUTO_INCREMENT = 1;
